### ISSUE TITLE
Problem with "de" locale and floating point numbers in style settings

### ISSUE THREAD

**Issue by texnixe** [SiteMarina/guggenheim#1]
When I first viewed a page with newly installed guggenheim plugin, there was nothing displayed on the page. As it turned out, the style settings were using commas in the German language site instead of points in floating point numbers, while the English site was perfectly alright.

When I added the LC_NUMERIC locale setting and set it to en_US, everything was fine. I would however prefer that to work independent of the site-wide locale settings, so that I can use language specific floating point numbers in the rest of my pages.

**Comment by JimmyRittenborg** [comment]
Oooh yeah, you're totally right about this @texnixe it currently requires you to

``` php
c::set('locale', array(
  LC_CTYPE  => 'en_US.utf8',
));
```

or maybe the LC_NUMERIC like you're saying, I ran into this myself at some point as I'm from Denmark, where we use comma as a decimal delimiter too. But in CSS the decimal delimiter HAS to be a period.

This will be fixed in the next update, coming very soon :+1:

**Comment by JimmyRittenborg** [comment]
This has now been fixed in version 1.0.4
